version: '{build}'
os: Visual Studio 2015
configuration: Release
build:
  project: Nest.Queryify.sln
  verbosity: minimal
after_build:
  cmd: nuget pack src/Nest.Queryify/Nest.Queryify.csproj -Version %GitVersion_NugetVersion% -IncludeReferencedProjects -Symbols -Properties "Configuration=%CONFIGURATION%" -Verbosity detailed
artifacts:
- path: Nest.Queryify.*.nupkg
cache: packages -> src\packages.config