version: '{build}'
os: Visual Studio 2015
configuration: Release
environment:
  solution_path: Nest.Queryify.sln
  project_path: src/Nest.Queryify/Nest.Queryify.csproj
build_script:
  - cmd: nuget restore %SOLUTION_PATH%
  - cmd: msbuild %SOLUTION_PATH% "/p:Configuration=%CONFIGURATION%"
  - cmd: nuget pack %PROJECT_PATH% -Version %GitVersion_NugetVersion% -IncludeReferencedProjects -Symbols -Properties "Configuration=%CONFIGURATION%" -Verbosity detailed
  - cmd: appveyor PushArtifact "Nest.Queryify.%GitVersion_NuGetVersion%.nupkg"
  - cmd: appveyor PushArtifact "Nest.Queryify.%GitVersion_NuGetVersion%.symbols.nupkg"
cache: packages -> src\packages.config