version: '{build}'
os: Visual Studio 2015
configuration: Release
build_script:
  - cmd: nuget restore Nest.Queryify.sln
  - cmd: msbuild Nest.Queryify.sln "/p:Configuration=%CONFIGURATION%"
  - cmd: nuget pack src/Nest.Queryify.csproj -Version %GitVersion_NugetVersion% -IncludeReferencedProjects -Symbols -Properties "Configuration=%CONFIGURATION%" -Verbosity detailed
  - cmd: appveyor PushArtifact "Nest.Queryify.%GitVersion_NuGetVersion%.nupkg"
  - cmd: appveyor PushArtifact "Nest.Queryify.%GitVersion_NuGetVersion%.symbols.nupkg"
cache: packages -> src\packages.config